/** @typedef {'A'|'B'|'C'|'D'} SourceLevel */
/** @typedef {{claim:string,sourceName:string,sourceUrl:string,sourceLevel:SourceLevel,publisher:string,checkedAt:string,status:'verified'|'needs_recheck'|'historical_reference'}} Evidence */
/** @typedef {{label:'local_regulars_verified'|'local_leaning'|'mixed_local_tourist'|'tourist_oriented',localScore:number,localReason:string,bestLocalTime?:string,etiquette?:string[],evidence:Evidence[]}} LocalExperience */
/** @typedef {{id:string,city:'fuzhou'|'quanzhou'|'chaozhou'|'shantou',category:string,name:string,editorialRating:number,culturalValue:number,experienceValue:number,commercialRisk:'low'|'medium'|'high',recommendationStatus:'core_recommendation'|'conditional_recommendation'|'candidate_only',recommendationReason:string,avoidIf:string[],suggestedDuration:string,bestTime:string,dateSensitive:boolean,verificationNote?:string,heritage?:{worldHeritage?:boolean,nationalKeyRelic?:boolean,museumLevel?:string},localExperience:LocalExperience,sources:Evidence[]}} Place */
const checked='2026-08-15',A=(claim,name,url)=>({claim,sourceName:name,sourceUrl:url,sourceLevel:'A',publisher:name,checkedAt:checked,status:'verified'}),B=(claim,name,url)=>({claim,sourceName:name,sourceUrl:url,sourceLevel:'B',publisher:name,checkedAt:checked,status:'verified'}),C=(claim,name,url)=>({claim,sourceName:name,sourceUrl:url,sourceLevel:'C',publisher:name,checkedAt:checked,status:'needs_recheck'}),D=(claim,name,url)=>({claim,sourceName:name,sourceUrl:url,sourceLevel:'D',publisher:name,checkedAt:checked,status:'needs_recheck'});
const sources={unesco:'https://whc.unesco.org/en/list/1561/',fj:'https://wlt.fujian.gov.cn/',museum:'https://app.gjzwfw.gov.cn/jmopen/webapp/html5/gjwwjqgbwgmlcxpc/index.html',ih:'https://www.ihchina.cn/project.html',shantou:'https://www.shantou.gov.cn/cnst/yxst/cszn/lyzn/jqjd/index.html'};
const cityGuides={
fuzhou:{name:'福州',kicker:'闽都 · 榕城 · 江海门户',intro:'福州是第二批国家历史文化名城，拥有2200多年建城史。闽江穿城、内河成网，古城、近代港口与山水格局共同构成城市底色。官方名城资料将昙石山文化、三坊七巷文化、船政文化和寿山石文化列为闽都文化的重要代表。',history:'福州的历史不只在三坊七巷。古代海上交通说明它长期面向海洋；晚清福建船政局及船政学堂则把福州带入近代造船、海军与实业教育史。林则徐、沈葆桢、严复、林觉民等人物，也让坊巷空间与中国近现代思想和社会变迁紧密相连。',character:'理解福州，适合沿“古城—商埠—船政”三条线展开：三坊七巷看士绅宅院与坊巷制度，上下杭和烟台山看商贸与近代城市，马尾看船政工业遗产。西湖、鼓山和闽江则补足“城在山水之间”的日常经验。',folk:['福州茉莉花与茶文化系统已被认定为全球重要农业文化遗产；窨制技艺、花茶贸易与城市生活相互关联。','寿山石雕于2006年列入首批国家级非物质文化遗产名录，观看作品时可重点留意“相石取巧、因材施艺”。','传统街区仍是生活和公共文化空间。参观古厝、宗祠或社区型场馆时，应保持安静，不占用居民出入口。'],food:'福州是闽菜重要发源地。官方文旅资料列出的代表菜与小吃包括佛跳墙、鸡汤汆海蚌、荔枝肉、鱼丸、肉燕、捞化与锅边。肉燕也与福州年节、婚寿宴席中的“太平燕”传统相关。初次体验可把汤食、小吃和一顿正式闽菜分开安排。',landmarks:['三坊七巷：古城历史结构与近现代人物线索。','福建博物院—西湖：建立福建历史与民间艺术背景。','上下杭—烟台山：商埠、会馆、近代建筑和闽江关系。','马尾船政：近代造船、海军与实业教育史。','鼓山—涌泉寺：山林、寺院与摩崖石刻。'],advice:'建议至少留两天：一天在鼓楼、台江和仓山慢走，另半天至一天前往马尾或鼓山。夏季湿热，多把室内馆安排在午后；古厝与展馆开放信息以官方当天公告为准。',sources:[{name:'福州市历史文化名城管委会｜国家历史文化名城：福建福州',url:'https://www.fuzhou.gov.cn/zgfzzt/lswhmcgwh/zwgk/ztzl/bhqy/202403/t20240315_4792675.htm'},{name:'福州市政府｜文旅局访谈：闽都美食与代表菜',url:'https://www.fuzhou.gov.cn/zgfzhd/zxft/wqhg/202109/t20210924_4195246.htm'},{name:'福州市方志委｜福州肉燕与太平燕',url:'https://www.fuzhou.gov.cn/zgfzzt/zjrc/mdfc/lswh/202210/t20221026_4457433.htm'},{name:'福州市名城委｜茉莉花茶文化馆',url:'https://www.fuzhou.gov.cn/zgfzzt/lswhmcgwh/zwgk/ztzl/bhqy/202504/t20250408_5001214.htm'}]},
quanzhou:{name:'泉州',kicker:'刺桐城 · 海丝名城 · 世界遗产城市',intro:'泉州是国务院首批公布的国家历史文化名城。2021年，“泉州：宋元中国的世界海洋商贸中心”列入《世界遗产名录》，系列遗产由生产、运输、销售、管理和多元社群等不同功能的遗产点共同构成，不能只理解为一条古街。',history:'宋元时期，泉州依靠港口、商品生产、交通网络和制度保障成为世界海洋商贸中心。开元寺、清净寺、天后宫、府文庙、德济门、洛阳桥、九日山等遗产点，呈现佛教、伊斯兰教、妈祖信仰、儒学与海洋贸易在同一城市中的共存。',character:'泉州最有价值的体验，是观察遗产仍如何嵌入日常：寺庙仍有香火，骑楼街仍在经营，南音与戏曲仍有传承场域。城市官方资料将其概括为开放、包容而多元，这种特质来自背山面海的地理条件与长期海贸传统。',folk:['进入寺庙、宫庙与清真寺时，应遵守各场所着装、摄影和礼仪规定；宗教空间不是单纯布景。','泉州拥有南音等丰富非遗。演出与公益场次会变化，应以文旅部门、场馆或传承机构公告为准。','古城街巷居民与游客共用。避开通勤高峰、轻声参观，更容易看到真实的城市生活。'],food:'泉州官方美食线路将面线糊、姜母鸭、烧肉粽、润饼、牛排、石花膏等串入古城与世遗路线。面线糊适合早餐，姜母鸭和闽南牛排更接近正餐；与其一次密集品尝，不如按街区和时段组合。',landmarks:['开元寺—西街—中山路：古城与日常商业骨架。','清净寺—关岳庙—府文庙：多元宗教和制度文化。','天后宫—德济门：港口、城门与海洋信仰。','海外交通史博物馆：补足海贸与跨文化交流背景。','洛阳桥或九日山：理解港口交通与祈风制度。'],advice:'建议古城至少留一整天，另留半天给海交馆、洛阳桥或清源山。世界遗产点的意义来自彼此关系，最好少选几个认真看，而不是把22个遗产点做成打卡清单。',sources:[{name:'泉州市人民政府｜泉州概况',url:'https://quanzhou.gov.cn/zfb/zjqz/qzgk/'},{name:'泉州市人民政府｜从历史文化名城到世界遗产城市',url:'https://www.quanzhou.gov.cn/zfb/xxgk/zfxxgkzl/qzdt/qzyw/202209/t20220907_2773409.htm'},{name:'UNESCO｜Quanzhou: Emporium of the World in Song-Yuan China',url:'https://whc.unesco.org/en/list/1561/'},{name:'泉州市文旅局｜十大泉州美食精品旅游线路',url:'https://quanzhou.gov.cn/lyb/lyxw/202601/t20260119_3258243.htm'}]},
chaozhou:{name:'潮州',kicker:'岭东古城 · 韩江府城 · 非遗之城',intro:'潮州是国家历史文化名城。自东晋设置海阳县以来，长期是粤东地区重要的郡、州、路、府治所；古城与韩江、城墙、街巷和传统工艺共同构成其历史环境。官方保护规划把潮州方言、潮剧、潮州音乐、工夫茶、潮州菜和潮绣等列为潮州文化的重要代表。',history:'潮州古城的核心不是单一牌坊街，而是府城格局：广济门与城墙面向韩江，广济桥连接两岸，开元寺、许驸马府、己略黄公祠等保存宗教、宅第和宗祠建筑传统。太平路的牌坊既记录科名与地方人物，也与两侧近代骑楼形成复合街景。',character:'潮州文化常被官方资料概括为崇文重教、精细讲究并具有开放性。它既承接中原文化传统，也在海洋交通、侨乡联系和地方工艺中形成鲜明面貌。旅行时应放慢节奏，通过一席茶、一次古建细看或一场正式演出理解“工夫”所代表的时间与技艺。',folk:['潮州工夫茶不仅是一种饮品，也是一套器具、冲泡与待客秩序。参加体验时先观察主人操作，不必急着自行摆弄茶具。','潮剧、潮州音乐、潮绣、潮州木雕、潮瓷与潮塑等构成重要非遗谱系；购买工艺品时可优先选择有传承人、工作室或官方展馆信息的渠道。','宗祠、寺庙与居民街巷仍在使用。遇到祭祀或民俗活动，不越线拍摄、不打断仪式。'],food:'潮州菜、潮州工夫茶及粿品共同构成饮食体验。官方资料强调潮州饮食精致讲究；牛肉火锅、卤味、粿条与各类粿品适合分时段、小份组合。喝工夫茶时无需追求昂贵茶叶，先理解冲泡秩序和当地待客方式更重要。',landmarks:['广济桥—广济门—韩江：城市与河流的核心关系。','牌坊街及其支巷：府城轴线、牌坊与骑楼。','开元寺：古城宗教与建筑文化。','许驸马府、己略黄公祠：宅第格局与木雕工艺。','潮州市博物馆或专题工艺馆：补足地方史与非遗背景。'],advice:'建议住在古城步行范围内但避开最喧闹的牌坊街主轴。清晨看古城生活，白天参观古建与博物馆，午后安排茶馆，傍晚再到韩江。广济桥开放、拆装浮桥和灯光安排以官方公告为准。',sources:[{name:'潮州市人民政府｜一桥一楼一街：历史和当代相得益彰',url:'https://www.chaozhou.gov.cn/slhwz/czxw/content/post_3880941.html'},{name:'潮州市人民政府｜潮州国家历史文化名城保护规划',url:'https://www.chaozhou.gov.cn/attachment/0/519/519450/3814125.pdf'},{name:'潮州市人民政府｜文化旅游资源与非遗情况',url:'https://www.chaozhou.gov.cn/zwgk/jytabl/content/post_3730686.html'}]},
shantou:{name:'汕头',kicker:'百载商埠 · 著名侨乡 · 海湾城市',intro:'汕头是一座向海而生、因港而立、因侨而兴的城市，也是国家首批经济特区。其城市叙事应从港口、开埠、华侨网络和改革开放四条线共同理解。韩江、榕江、练江在此入海，内海湾塑造了城市的空间与生活方式。',history:'汕头从沿海聚落发展为通商口岸，近代港口、邮电、铁路和城市公共设施快速形成。小公园开埠区保存放射状街巷与成片骑楼，聚集洋行、商会、旅社、影院和侨批相关遗存；这些建筑背后，是海外潮人与家乡之间长期的资金、书信和社会联系。',character:'汕头的文化由海洋文化、侨乡文化、商埠文化、潮汕传统与经济特区精神叠合而成。小公园不是复古布景，而是理解近代商业和侨乡社会的入口；西堤、内海湾与轮渡则让港口城市的地理关系变得直观。',folk:['侨批由书信与汇款凭证构成，是理解海外潮人家庭责任、商业网络与家国联系的重要材料；建议把侨批文物馆与开埠文化陈列馆一起看。','潮剧、潮州音乐、英歌、工夫茶以及潮绣、金漆木雕等，属于汕头官方城市文化介绍中的重要内容。活动时间需以政府或主办单位公告为准。','老城仍有居民和商户。拍摄骑楼、市场与老宅时应尊重私人空间，避免堵塞店门与街巷。'],food:'汕头市政府列出的代表菜和小吃包括卤狮头鹅、潮汕鱼饭、汕头牛肉丸、达濠鱼丸、粿品、粽球、蚝烙、肠粉与鸭母捻等。更合适的吃法是早餐安排肠粉或粿条，正餐选择牛肉、卤鹅或潮菜，再把甜品作为散步停顿。',landmarks:['小公园开埠区：近代商埠、骑楼和放射状街巷。','开埠文化陈列馆—侨批文物馆：城市开放史与侨乡网络。','西堤公园—观海长廊：港口与内海湾关系。','汕头市博物馆—中山公园：地方史与城市公共生活。','礐石或妈屿岛：从山海与轮渡角度观察城市。'],advice:'建议把小公园安排在上午或傍晚，避开正午暴晒；至少用半天串联两座主题馆和骑楼街区。南澳岛应单独占用一天，并在临行前核对天气、道路和海上预警。',sources:[{name:'汕头市人民政府｜城市历史与文化概况',url:'https://www.shantou.gov.cn/stscgj/gkmlpt/content/2/2279/post_2279608.html'},{name:'汕头市政府英文网｜民俗文化概述',url:'https://english.shantou.gov.cn/english/%EF%BB%BFoverview/localculture/cultural/content/post_783895.html'},{name:'汕头市交通运输局｜小公园开埠区历史建筑',url:'https://www.shantou.gov.cn/stsjtysj/gkmlpt/content/2/2307/mpost_2307097.html'},{name:'汕头市人民政府｜名菜名小吃',url:'https://www.shantou.gov.cn/cnst/yxst/cszn/lyzn/mcmxc/index.html'}]}
};
const p=(id,city,category,name,status,reason,heritage,local,extra={})=>({id,city,category,name,editorialRating:extra.rating||4.4,culturalValue:extra.cultural||4.5,experienceValue:extra.experience||4.2,commercialRisk:extra.risk||'low',recommendationStatus:status,recommendationReason:reason,avoidIf:extra.avoidIf||[],suggestedDuration:extra.duration||'1–2 小时',bestTime:extra.bestTime||'上午或傍晚',dateSensitive:!!extra.dateSensitive,verificationNote:extra.note,heritage,localExperience:local,sources:extra.sources||local.evidence});
const mix=(r,e)=>({label:'mixed_local_tourist',localScore:3.8,localReason:r,bestLocalTime:e,evidence:[A('文化资源与保护信息','福建省文化和旅游厅',sources.fj)]});
const lean=(r,e)=>({label:'local_leaning',localScore:3.5,localReason:r,bestLocalTime:e,evidence:[C('近期开放与活动需复核','场馆/经营方信息',sources.fj)]});
const places=[
p('fz-sfqx','fuzhou','attraction','三坊七巷','core_recommendation','福州城市历史结构的核心入口；游客多，但仍值得作为理解坊巷制度的骨架。',{nationalKeyRelic:true},mix('核心历史街区，本地与游客共同使用。','清晨工作日前往'),{rating:4.8,cultural:4.9,sources:[A('福州历史文化资源','福建省文化和旅游厅',sources.fj)]}),
p('fz-museum','fuzhou','museum','福建博物院','core_recommendation','以省级综合馆建立福建历史、海洋与民间艺术的基础认知。',{museumLevel:'国家一级'},mix('公共文化机构，有稳定本地教育与休闲功能。','雨天上午'),{rating:4.7,sources:[A('博物馆等级与名录','国家文物局政务服务平台',sources.museum)]}),
p('fz-ship','fuzhou','attraction','中国船政文化博物馆与马尾船政旧址','core_recommendation','理解近代中国造船、海军与教育史的高价值组合。',{nationalKeyRelic:true},mix('文化目的地，本地与游客共用。','工作日上午'),{rating:4.8,sources:[A('船政文化景区资格与资源信息','福建省文化和旅游厅',sources.fj)]}),
p('fz-walk','fuzhou','walk','上下杭—闽江步行线','conditional_recommendation','用旧商埠、会馆与江岸把福州商业史和当代生活连接起来。',{},lean('适合傍晚散步，能看到江边公共生活。','傍晚遛弯'),{rating:4.3,duration:'2 小时',dateSensitive:false}),
p('qz-wh','quanzhou','world_heritage','宋元中国的世界海洋商贸中心（古城世遗步行线）','core_recommendation','世界遗产是理解泉州的文化骨架；跨城专程安排的理由是港口、宗教与城市制度形成完整系统。',{worldHeritage:true},mix('核心遗产和日常街区重叠，本地与游客共用。','清晨开元寺至中山路'),{rating:5,cultural:5,sources:[A('世界遗产价值与2021年列入名录','UNESCO World Heritage Centre',sources.unesco)]}),
p('qz-sea','quanzhou','museum','泉州海外交通史博物馆','core_recommendation','将海上贸易、宗教交流和海外交通的叙事补全。',{museumLevel:'国家一级'},mix('公共博物馆，适合雨天与慢节奏学习。','雨天上午'),{rating:4.9,sources:[A('博物馆名录','国家文物局政务服务平台',sources.museum)]}),
p('qz-luoyang','quanzhou','world_heritage','洛阳桥与桥南古街','core_recommendation','桥梁、港口与聚落关系是泉州世遗系统的重要一环。',{worldHeritage:true,nationalKeyRelic:true},mix('本地通行与文化参访交织。','傍晚'),{rating:4.7,sources:[A('世界遗产系列组成部分','UNESCO World Heritage Centre',sources.unesco)]}),
p('qz-nanyin','quanzhou','neighborhood','古城南音馆阁（活动型推荐）','conditional_recommendation','南音是理解泉州的重要入口；仅在已确认的演出、讲解或体验场次开放时安排。',{},lean('如有正式演出，适合以在地音乐理解古城。','演出日夜间'),{dateSensitive:true,note:'出发前 7 天确认场次、地点与预约。',sources:[A('南音非遗项目','中国非物质文化遗产网',sources.ih)]}),
p('cz-gj','chaozhou','national_key_relic','广济桥','core_recommendation','桥、韩江与古城空间关系是潮州城市形成的关键；值得专程安排。',{nationalKeyRelic:true},mix('本地与游客共同使用的城市地标。','午后至傍晚'),{rating:4.8,sources:[A('文化资源资格与开放信息','广东省/潮州文旅主管部门',sources.shantou)]}),
p('cz-museum','chaozhou','museum','潮州市博物馆','conditional_recommendation','陶瓷、木雕与地方民俗可为古城步行补足物质文化背景。',{},mix('公共文化空间，适合雨天。','雨天上午'),{rating:4.3,dateSensitive:true,note:'出发前 7 天复核展览与开放时间。',sources:[A('博物馆名录核验入口','国家文物局政务服务平台',sources.museum)]}),
p('cz-walk','chaozhou','walk','韩江—牌坊街—开元寺步行线','conditional_recommendation','把河流、桥梁、街巷和宗教空间串为一条可步行理解的城市线。',{},mix('白天可见居民生活，夜间游客密度更高。','工作日下午'),{rating:4.5,duration:'2–3 小时'}),
p('cz-book','chaozhou','bookstore','时间轴书店','conditional_recommendation','古城里的阅读与潮州主题选书，为步行路线提供一段安静的文化休息。',{},lean('若有地方文化读书会，可作为古城弹性休息段。','活动日午后'),{dateSensitive:true,note:'书店与活动信息需在出发前 7 天复核。',sources:[D('书店位置、选书与空间描述','群学书院探访文章','https://www.sohu.com/a/679902788_120271802')]}),
p('st-park','shantou','neighborhood','小公园开埠区—侨批文物馆步行线','core_recommendation','近代开埠、骑楼与侨批网络构成理解汕头的核心文化骨架。',{},mix('老城仍有日常商业与居民活动，但游客密度会上升。','上午或傍晚'),{rating:4.7,duration:'2–3 小时',sources:[A('小公园开埠区资源介绍','汕头市人民政府',sources.shantou)]}),
p('st-museum','shantou','museum','汕头市博物馆','conditional_recommendation','以地方史和开埠叙事补足老城步行线的历史背景。',{museumLevel:'国家二级'},mix('公共博物馆，适合雨天。','雨天上午'),{dateSensitive:true,note:'出发前 7 天复核开放与展览。',sources:[A('博物馆名录核验入口','国家文物局政务服务平台',sources.museum)]}),
p('st-island','shantou','park','南澳岛生态旅游区','conditional_recommendation','海岛地貌与渔业生活值得看，但天气、轮渡与道路条件决定可用性。',{},lean('避开周末高峰，以海边公共空间和渔港观察为主。','非周末清晨'),{rating:4.2,risk:'medium',dateSensitive:true,note:'出发前 7 天复核天气、海岛交通与预警。',sources:[A('汕头景区资源信息','汕头市人民政府',sources.shantou)]}),
p('st-market','shantou','market','老城早餐与市场时段','conditional_recommendation','把它作为一段“观察当地早晨”的弹性路线，而非追逐某个摊位；不进入居民私密空间。',{},lean('仅在不打扰经营和居民生活的前提下观察与消费。','工作日早餐'),{dateSensitive:true,note:'具体市场与摊位必须出发前 7 天确认。',sources:[C('近期状态待复核','经营方/地图信息',sources.shantou)]}),
p('fz-yantai','fuzhou','neighborhood','烟台山历史风貌区','conditional_recommendation','近代建筑、江景和当代文化空间并置，适合作为理解福州近代城市生活的一段步行。',{},mix('白天居民、访客与文化消费共用。','工作日下午'),{rating:4.5,duration:'2–3 小时',sources:[A('福州古厝保护提升重点区域','福建省人民政府', 'https://www.fujian.gov.cn/zwgk/zfxxgk/szfwj/szfgz/202109/P020210909330842035824.pdf')]}),
p('fz-westlake','fuzhou','park','西湖公园—福建博物院散步线','conditional_recommendation','不以打卡为目标，把省博参观和本地公共公园散步组合为雨后或午后的缓冲段。',{},lean('公共公园，适合观察城市的日常休闲节奏。','傍晚'),{rating:4.3,duration:'2 小时'}),
p('fz-yonghe','fuzhou','food','永和鱼丸','conditional_recommendation','代表性小吃可作为城市饮食样本，而不是整趟旅程的唯一目的地。',{},mix('老字号门店兼有本地与游客客流。','工作日早餐'),{rating:4.2,dateSensitive:true,note:'门店、排队和营业时间出发前 7 天复核。',sources:[C('门店与小吃信息','福州本地宝','https://fz.bendibao.com/tour/202397/70659.shtm'),D('近期体验交叉核验','Trip.com','https://hk.trip.com/guide/destination/%E7%A6%8F%E5%B7%9E%E4%B8%89%E5%9D%8A%E4%B8%83%E5%B7%B7.html')]}),
p('qz-kaiyuan','quanzhou','world_heritage','开元寺','core_recommendation','泉州古城世遗步行的起点；宗教建筑、城市格局与日常香火共同解释海丝城市。',{worldHeritage:true,nationalKeyRelic:true},mix('宗教空间与参访空间并存。','清晨'),{rating:4.9,sources:[A('世界遗产系列组成部分','UNESCO World Heritage Centre',sources.unesco)]}),
p('qz-qingjing','quanzhou','world_heritage','清净寺','core_recommendation','跨文化交流在城市空间中留下的直接证据，应与开元寺、天后宫串联理解。',{worldHeritage:true,nationalKeyRelic:true},mix('宗教场所，参访请保持安静。','上午'),{rating:4.8,sources:[A('世界遗产系列组成部分','UNESCO World Heritage Centre',sources.unesco)]}),
p('qz-food','quanzhou','food','侯阿婆肉粽','conditional_recommendation','一枚肉粽能连接端午、街巷与泉州人的家常记忆；作为步行间隙而非网红冲刺。',{},mix('长期经营的老字号，同时面对本地与游客。','上午或下午避开饭点'),{rating:4.5,dateSensitive:true,note:'营业与排队情况出发前 7 天复核。',sources:[B('老字号经营与地方饮食记忆','泉州世界美食之都官方站','https://www.quanzhou.gov.cn/gastronomy/ch/msdh/xwqz/202606/t20260616_3300830.htm')]}),
p('cz-han','chaozhou','attraction','韩文公祠—韩江步行线','conditional_recommendation','把韩江景观、古城书写传统和潮州地方记忆放进同一段步行，比只逛牌坊街更完整。',{},mix('文化参访与城市散步共用。','上午或傍晚'),{rating:4.5,duration:'2 小时',sources:[A('潮州文化旅游资源核验入口','潮州/广东文旅主管部门','https://www.gdfao.gov.cn/zwgk/zdly/sts/content/post_1333373.html')]}),
p('cz-ceramic','chaozhou','museum','颐陶轩潮州窑博物馆','conditional_recommendation','以潮州窑、陶瓷和工艺史补足“瓷都”经验；适合对手作与器物感兴趣的人。',{},lean('专题文化空间，适合与古城慢走搭配。','雨天或午后'),{rating:4.4,dateSensitive:true,note:'展览和开放信息出发前 7 天复核。',sources:[C('开放与展陈须复核','场馆信息',sources.museum)]}),
p('cz-food','chaozhou','food','胡荣泉','conditional_recommendation','潮州小食是城市饮食语汇的一部分；适合与古城步行穿插，不以排队长度作为价值判断。',{},mix('知名小食店，本地与游客共用。','非正餐时段'),{rating:4.2,dateSensitive:true,note:'菜单、营业与排队出发前 7 天复核。',sources:[D('近期运营与体验交叉核验','旅行平台/地图信息','https://www.amap.com/')]}),
p('st-chen','shantou','attraction','陈慈黉故居','conditional_recommendation','以侨居建筑理解潮汕侨乡社会和近代家庭网络，适合半日深度停留。',{},lean('文化参访为主，宜和老城开埠线错日安排。','上午'),{rating:4.5,duration:'2–3 小时',sources:[A('汕头旅游资源入口','汕头市人民政府',sources.shantou)]}),
p('st-mayu','shantou','park','妈屿岛海边散步','conditional_recommendation','将港口、海风与城市公共空间放进半日松弛段；不必把它做成拍照任务。',{},lean('海边日常空间，适合低密度慢走。','日落前'),{rating:4.2,dateSensitive:true,note:'出发前 7 天复核天气、交通与开放情况。',sources:[A('汕头景区资源信息','汕头市人民政府',sources.shantou)]}),
p('st-food','shantou','food','老妈宫粽球','conditional_recommendation','老字号粽球可与小公园开埠区并行理解，而不是单独为排队而去。',{},mix('本地老字号，也吸引游客。','工作日上午'),{rating:4.4,dateSensitive:true,note:'营业情况出发前 7 天复核。',sources:[A('老字号与潮汕饮食文化','汕头市人民政府','https://www.shantou.gov.cn/gzw/zwgk/gzdt/content/post_2520876.html')]}),
p('qz-xiaoxicheng','quanzhou','cafe','小西埕文创街区','conditional_recommendation','适合在西街路线中短暂停留喝咖啡、看文创，但网红拍照属性强，不建议单独专程。',{}, {label:'tourist_oriented',localScore:2.2,localReason:'游客导向明显，作为弹性休息点更合适。',bestLocalTime:'工作日下午',evidence:[D('旅行者对文创、咖啡和网红属性的描述','马蜂窝游记','https://itf.mafengwo.cn/client/note.php/info/?id=24038524')]},{rating:3.9,risk:'high',dateSensitive:true,note:'具体店铺营业需复核。',sources:[D('旅行者对文创、咖啡和网红属性的描述','马蜂窝游记','https://itf.mafengwo.cn/client/note.php/info/?id=24038524')]}),
p('cz-coffee','chaozhou','cafe','小雅岩烧咖啡（电信路店）','conditional_recommendation','古城行程中的咖啡休息点；进入推荐来自旅行者平台的多语言可见度，不赋予文化遗产意义。',{},lean('适合在广济桥与牌坊街之间休息。','下午'),{rating:4.1,dateSensitive:true,note:'营业与座位需复核。',sources:[D('广济桥周边餐饮推荐','Tripadvisor','https://cn.tripadvisor.com/RestaurantsNear-g303698-d1864475-Guangji_Bridge-Chaozhou_Guangdong.html')]}),
p('st-temp','shantou','cafe','Temp Coffee','conditional_recommendation','小公园城市漫游中被中文社交内容反复提及的咖啡休息点，适合作为骑楼路线的弹性段。',{},lean('偏旅行者城市漫游体验，是否为本地日常仍不作断言。','下午'),{rating:4.2,dateSensitive:true,note:'营业、地址与排队出发前 7 天复核。',sources:[D('小红书路线聚合与近期攻略交叉信息','什么值得买旅行攻略','https://post.smzdm.com/p/aqrpx467/')]}),
p('st-post18','shantou','cafe','post 18g coffee','conditional_recommendation','适合与开埠文化陈列馆、小公园串联的咖啡休息点；文化价值来自路线位置，不来自店铺本身。',{},lean('偏城市漫游体验。','下午'),{rating:4.1,dateSensitive:true,note:'营业、地址与排队出发前 7 天复核。',sources:[D('小红书路线聚合与近期攻略交叉信息','什么值得买旅行攻略','https://post.smzdm.com/p/aqrpx467/')]}),
p('st-yiniao','shantou','bookstore','壹茑书巢','conditional_recommendation','24小时书店概念与咖啡阅读空间曾形成城市文化印象，适合作为雨天或夜间弹性段。',{},lean('阅读空间比纯打卡更适合慢旅行。','傍晚或雨天'),{rating:4.2,dateSensitive:true,note:'旧资料较早，必须出发前确认是否仍营业及地址。',sources:[D('书店空间、地址和历史营业信息','汕头本地宝','https://m.st.bendibao.com/tour/2843.shtm')]})];
